setup/urls.py
from django.urls import path
from django.conf.urls.static import static
from setup import settings

from filmes.views import FilmeCreateView, FilmeDeleteView, FilmeDetailView, FilmeListView, FilmeUpdateView, GeneroCreateView, GeneroDeleteView, GeneroDetailView, GeneroListView, GeneroUpdateView

urlpatterns = [
    path('', GeneroListView.as_view(), name='genero_list'),
    path('create/', GeneroCreateView.as_view(), name='genero_create'),
    path('<int:pk>/', GeneroDetailView.as_view(), name='genero_detail'),
    path('<int:pk>/edit/', GeneroUpdateView.as_view(), name='genero_update'),
    path('<int:pk>/delete/', GeneroDeleteView.as_view(), name='genero_delete'),

    path('filmes/', FilmeListView.as_view(), name='filme_list'),
    path('filmes/create/', FilmeCreateView.as_view(), name='filme_create'),
    path('<int:pk>/', FilmeDetailView.as_view(), name='filme_detail'),
    path('<int:pk>/edit/', FilmeUpdateView.as_view(), name='filme_update'),
    path('<int:pk>/delete/', FilmeDeleteView.as_view(), name='filme_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmes/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    direcao = models.CharField(max_length=100)
    distribuicao = models.CharField(max_length=100, blank=True)
    capa = models.ImageField(upload_to='capas/', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return f"{self.titulo} {self.direcao}"
    
class Genero(models.Model):
    nome = models.CharField(max_length=100)
    filmes = models.ManyToManyField(Filme)

    def __str__(self):
        return self.nome

filmes/forms.py
from django import forms 
from .models import Genero, Filme

class GeneroForm(forms.ModelForm):
    class Meta:
        model = Genero
        fields = '__all__'

class FilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = '__all__'

filmes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from filmes.forms import FilmeForm, GeneroForm
from filmes.models import Filme, Genero

class GeneroListView(ListView):
    model = Genero
    template_name = 'genero/genero_list.html'
    context_object_name = 'generos'
    paginate_by = 8
    queryset = Genero.objects.order_by('-id')

class GeneroDetailView(DetailView):
    model = Genero
    template_name = 'genero/genero_detail.html'

class GeneroCreateView(CreateView):
    model = Genero
    form_class = GeneroForm
    template_name = 'genero/genero_form.html'
    success_url = reverse_lazy('genero_list')

class GeneroUpdateView(UpdateView):
    model = Genero
    fields = ['nome', 'filmes']
    template_name = 'genero/genero_form.html'
    success_url = reverse_lazy('genero_list')

class GeneroDeleteView(DeleteView):
    model = Genero
    template_name = 'genero/genero_confirm_delete.html'
    success_url = reverse_lazy('genero_list')

class FilmeListView(ListView):
    model = Filme
    template_name = 'filmes/filme_list.html'

class FilmeDetailView(DetailView):
    model = Filme
    template_name = 'filmes/filme_detail.html'
    
class FilmeCreateView(CreateView):
    model = Filme
    form_class = FilmeForm
    template_name = 'filmes/filme_form.html'
    success_url= reverse_lazy('filme_list')

class FilmeUpdateView(UpdateView):
    model = Filme
    form_class = FilmeForm
    template_name = 'filmes/filme_form.html'
    success_url = reverse_lazy('filme_list')

class FilmeDeleteView(DeleteView):
    model = Filme
    template_name = 'filmes/filme_confirm_delete.html'
    success_url = reverse_lazy('filme_list')

filmes/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand"  
 href="#">Meu Projeto de Generos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'genero_list' %}">Generos</a>
                    </li>
                    <li> <a class="nav-link active" aria-current="page" href="{% url 'filme_list' %}">Filmes</a></li>
                    </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

filmes/templates/filmes/filme_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir esse genero "{{ object.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'genero_detail' object.pk %}">Não</a>
</form>

{% endblock %}

filmes/templates/filmes/filme_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ object.titulo }}</h2>
<p>Artista: {{ object.direcao }}</p>
<p>Álbum: {{ object.distribuicao }}</p>
<p>Playlists:
    {% for genero in object.genero_set.all %}
        {{ genero.nome }}
    {% endfor %}
</p>

{% endblock %}

filmes/templates/filmes/filme_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Filme</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

filmes/templates/filmes/filme_list.html
{% extends 'base.html' %}

{% block content %}

<h2>Todos os Filmes</h2>

<a href="{% url 'filme_create' %}" class="btn btn-primary mb-3">Criar Filme</a>

<ul>
    {% for filme in object_list %}
        <li>{{ filme.titulo }} - {{ filme.artista }}
            <img src="{{ filme.capa.url }}" alt="{{ filme.titulo }}" width=100>
            <a href="{% url 'filme_detail' filme.pk %}" class="btn btn-primary">Detalhes</a>
            <a href="{% url 'filme_update' filme.pk %}" class="btn btn-secondary">Editar</a>
            <a href="{% url 'filme_delete' filme.pk %}" class="btn btn-danger">Excluir</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

filmes/templates/genero/genero_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir o "{{ object.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'genero_detail' object.pk %}">Não</a>
</form>

{% endblock %}

filmes/templates/genero/genero_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ object.nome }}</h2>
<ul>
    {% for filme in object.filmes.all %}
    <li>{{ filme.titulo }} - {{ filme.direcao }} - <img src="{{ filme.capa.url }}" alt="{{ filme.titulo }}" width=100></li>
    {% endfor %}
</ul>
<a href="{% url 'genero_update' object.pk %}">Editar</a>
<a href="{% url 'genero_delete' object.pk %}">Excluir</a>

{% endblock %}

filmes/templates/genero/genero_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Genero</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

filmes/templates/genero/genero_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'genero_create' %}"class="btn btn-primary mb-3">Criar Genero</a>

{% for genero in object_list %}
    <li>
        {{ genero.nome }}
       
        <a href="{% url 'genero_detail' genero.pk %}">Detalhes</a>
        <a href="{% url 'genero_update' genero.pk %}">Editar</a>
        <a href="{% url 'genero_delete' genero.pk %}">Excluir</a>
    </li>
    {% endfor %}
</ul>

<!-- Paginação -->
<nav aria-label="Navegação de páginas">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="Primeira">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;&laquo;</span></li>
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}

        <li class="page-item active">
            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próxima">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            <li class="page-item disabled"><span class="page-link">&raquo;&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
</div>

{% endblock %}